# Generated by Django 3.2.5 on 2021-07-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_employee_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
